CREATE TABLE public.contacts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  name text,
  email text,
  message text
);

ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;

-- If needed, allow anon inserts (since it's a contact form)
CREATE POLICY "Allow public insert" ON public.contacts FOR INSERT WITH CHECK (true);
